# Generated by Django 4.1.2 on 2024-02-19 17:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_category_post_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="date_ended",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
