# Generated by Django 4.1.2 on 2024-02-19 18:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_post_date_ended"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="date_ended",
        ),
        migrations.AddField(
            model_name="post",
            name="date_ended_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
