# Generated by Django 4.1.2 on 2024-02-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_remove_post_date_ended_post_date_ended_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="date_ended_date",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
