# Generated by Django 4.1.2 on 2024-02-19 18:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0007_alter_post_date_ended_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="ended_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
