# Generated by Django 4.1.2 on 2024-02-19 18:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0008_post_ended_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="date_ended_date",
        ),
        migrations.RemoveField(
            model_name="post",
            name="ended_time",
        ),
        migrations.AddField(
            model_name="post",
            name="date_ended",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
