# Generated by Django 4.1.2 on 2024-02-19 19:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0009_remove_post_date_ended_date_remove_post_ended_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="time_ended",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="date_ended",
            field=models.DateField(blank=True, null=True),
        ),
    ]
