# Generated by Django 4.1.2 on 2024-02-19 19:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0010_post_time_ended_alter_post_date_ended"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="date_ended",
            new_name="date_ended_date",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="time_ended",
            new_name="date_ended_time",
        ),
    ]
