# Generated by Django 4.1.2 on 2024-02-19 19:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0011_rename_date_ended_post_date_ended_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="date_ended_date",
        ),
        migrations.RemoveField(
            model_name="post",
            name="date_ended_time",
        ),
        migrations.AddField(
            model_name="post",
            name="date_ended",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
    ]
