# Generated by Django 4.1.2 on 2024-02-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0012_remove_post_date_ended_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="date_ended",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
