# Generated by Django 4.1.2 on 2024-02-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0014_post_participants"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="max_participants",
            field=models.IntegerField(null=True),
        ),
    ]
