# Generated by Django 4.1.2 on 2024-02-20 18:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0015_post_max_participants"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="max_participants",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
